services:
  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    restart: unless-stopped